services:
  influxdb3:
    image: influxdb:3-core
    container_name: influxdb3
    restart: unless-stopped
    ports:
      - "${INFLUXDB_PORT:-8181}:8181"
    environment:
      INFLUXDB3_NODE_ID: ${INFLUXDB3_NODE_ID:-node0}
    volumes:
      - influxdb3_data:/var/lib/influxdb3
    command:
      - serve
      - --node-id=${INFLUXDB3_NODE_ID:-node0}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3

  influxdb3-ui:
    image: influxdata/influxdb3-ui:latest
    container_name: influxdb3-ui
    restart: unless-stopped
    ports:
      - "${INFLUXDB_UI_PORT:-8282}:3000"
    environment:
      INFLUXDB3_HOST: http://influxdb3:8181
    depends_on:
      - influxdb3

volumes:
  influxdb3_data:
    name: influxdb3_data
