services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "${HOST_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

volumes:
  postgres_db_data:
    name: postgres-db-for-optimization-course
